spring:
    application:
        name: auth-service
    data:
        mongodb:
            host: 127.0.0.1
            port: 27017
            database: purely_auth_service
    jpa:
        hibernate:
            ddl-auto: update

server:
    port: ${AUTH_SERVICE_PORT:9030}

eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka/}
