services:
  # User service
  user-service:
    build:
      context: ./user-service
    container_name: user-service
    restart: always
    ports:
      - "8001:9050"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/user_db
    depends_on:
      - postgres
    networks:
      - microservice-network

  # Product service
  product-service:
    build:
      context: ./product-service
    container_name: product-service
    restart: always
    ports:
      - "8002:9010"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/product_db
    depends_on:
      - postgres
    networks:
      - microservice-network

  # Order service
  order-service:
    build:
      context: ./order-service
    container_name: order-service
    restart: always
    ports:
      - "8003:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/order_db
      - USER_SERVICE_URL=http://user-service:8000
      - PRODUCT_SERVICE_URL=http://product-service:8000
    depends_on:
      - postgres
      - user-service
      - product-service
    networks:
      - microservice-network

  # API Gateway
  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    restart: always
    ports:
      - "8000:8000"
    environment:
      - USER_SERVICE_URL=http://user-service:8000
      - PRODUCT_SERVICE_URL=http://product-service:8000
      - ORDER_SERVICE_URL=http://order-service:8000
    depends_on:
      - user-service
      - product-service
      - order-service
    networks:
      - microservice-network

  # Database service
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_DATABASES=user_db,product_db,order_db
    volumes:
      - ./scripts/create-multiple-postgresql-databases.sh:/docker-entrypoint-initdb.d/create-multiple-postgresql-databases.sh
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - microservice-network

networks:
  microservice-network:
    driver: bridge

volumes:
  postgres-data: