services:
  service-registry:
    build:
      context: ./service-registry
      dockerfile: Dockerfile
      args:
        - SERVICE_REGISTRY_PORT=${SERVICE_REGISTRY_PORT}
    ports:
      - ${SERVICE_REGISTRY_PORT}:${SERVICE_REGISTRY_PORT}
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:${SERVICE_REGISTRY_PORT}/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - microservice-network
      
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
      args:
        - API_GATEWAY_PORT=${API_GATEWAY_PORT}
        - SERVICE_REGISTRY_SERVICE_URL=${SERVICE_REGISTRY_SERVICE_URL}
        - SERVICE_REGISTRY_HOSTNAME=${SERVICE_REGISTRY_HOSTNAME}
    ports:
      - ${API_GATEWAY_PORT}:${API_GATEWAY_PORT}
    depends_on:
      service-registry:
        condition: service_healthy
    networks: 
      - microservice-network

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
      args:
        - USER_SERVICE_PORT=${USER_SERVICE_PORT}
        - MONGODB_HOST=${MONGODB_HOST}
        - MONGODB_PORT=${MONGODB_PORT}
        - MONGODB_DATABASE=${MONGODB_DATABASE}
        - SERVICE_REGISTRY_SERVICE_URL=${SERVICE_REGISTRY_SERVICE_URL}
    ports:
      - ${USER_SERVICE_PORT}:${USER_SERVICE_PORT}
    depends_on:
      service-registry:
        condition: service_healthy
      mongodb:
        condition: service_started
    networks: 
      - microservice-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - microservice-network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - microservice-network

  # Product service
  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
      args:
        - PRODUCT_SERVICE_PORT=${PRODUCT_SERVICE_PORT}
        - MONGODB_HOST=${MONGODB_HOST}
        - MONGODB_PORT=${MONGODB_PORT}
        - MONGODB_DATABASE=${MONGODB_DATABASE}
        - SERVICE_REGISTRY_SERVICE_URL=${SERVICE_REGISTRY_SERVICE_URL}


    container_name: product-service
    restart: always
    ports:
      - "${PRODUCT_SERVICE_PORT}:${PRODUCT_SERVICE_PORT}"
    networks:
      - microservice-network

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
      args:
        - NOTIFICATION_SERVICE_PORT=${NOTIFICATION_SERVICE_PORT}
        - SMTP_SERVER_URL=${SMTP_SERVER_URL}
        - SMTP_SERVER_PORT=${SMTP_SERVER_PORT}
        - EMAIL_USERNAME=${EMAIL_USERNAME}
        - EMAIL_PASSWORD=${EMAIL_PASSWORD}
        - SERVICE_REGISTRY_HOSTNAME=${SERVICE_REGISTRY_HOSTNAME}
        - SERVICE_REGISTRY_SERVICE_URL=${SERVICE_REGISTRY_SERVICE_URL}
    container_name: notification-service
    restart: always
    ports:
      - "${NOTIFICATION_SERVICE_PORT}:${NOTIFICATION_SERVICE_PORT}"
    depends_on:
      service-registry:
        condition: service_healthy  
    networks:
      - microservice-network

  # Order service
  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
      args:
        - ORDER_SERVICE_PORT=${ORDER_SERVICE_PORT}
        - MONGODB_HOST=${MONGODB_HOST}
        - MONGODB_PORT=${MONGODB_PORT}
        - MONGODB_DATABASE=${MONGODB_DATABASE}
        - SERVICE_REGISTRY_SERVICE_URL=${SERVICE_REGISTRY_SERVICE_URL}
        - SERVICE_REGISTRY_HOSTNAME=${SERVICE_REGISTRY_HOSTNAME}
    ports:
      - ${ORDER_SERVICE_PORT}:${ORDER_SERVICE_PORT}
    depends_on:
      service-registry:
        condition: service_healthy
      mongodb:
        condition: service_started
    networks: 
      - microservice-network
  #Category service
  category-service:
    build:
      context: ./category-service
      dockerfile: Dockerfile
      args:
        - CATEGORY_SERVICE_PORT=${CATEGORY_SERVICE_PORT}
        - MONGODB_HOST=${MONGODB_HOST}
        - MONGODB_PORT=${MONGODB_PORT}
        - MONGODB_DATABASE=${MONGODB_DATABASE}
        - SERVICE_REGISTRY_SERVICE_URL=${SERVICE_REGISTRY_SERVICE_URL}
    ports:
      - ${CATEGORY_SERVICE_PORT}:${CATEGORY_SERVICE_PORT}
    depends_on:
      service-registry:
        condition: service_healthy
      mongodb:
        condition: service_started
    networks: 
      - microservice-network
  cart-service:
    build:
      context: ./cart-service
      dockerfile: Dockerfile
      args:
        - CART_SERVICE_PORT=${CART_SERVICE_PORT}
        - MONGODB_HOST=${MONGODB_HOST}
        - MONGODB_PORT=${MONGODB_PORT}
        - MONGODB_DATABASE=${MONGODB_DATABASE}
        - SERVICE_REGISTRY_SERVICE_URL=${SERVICE_REGISTRY_SERVICE_URL}
    ports:
      - ${CART_SERVICE_PORT}:${CART_SERVICE_PORT}
    depends_on:
      service-registry:
        condition: service_healthy
      mongodb:
        condition: service_started
    networks: 
      - microservice-network

networks:
  microservice-network:
    driver: bridge

volumes:
  mongodb_data:
