spring:
    application:
        name: cart-service
    data:
        mongodb:
            host: ${MONGODB_HOST:127.0.0.1}
            port: ${MONGODB_PORT:27017}
            database: ${MONGODB_DATABASE:purely_cart_service}
            username: ${MONGODB_USERNAME:admin}
            password: ${MONGODB_PASSWORD:password}
            authentication-database: ${MONGODB_AUTHSOURCE:admin}
    jpa:
        hibernate:
            ddl-auto: update

server:
    port: ${CART_SERVICE_PORT:9000}

eureka:
    client:
        serviceUrl:
            defaultZone: ${SERVICE_REGISTRY_SERVICE_URL:http://localhost:8761/eureka/}
    instance:
        hostname: ${SERVICE_REGISTRY_HOSTNAME:localhost}