spring:
    application:
        name: cart-service
    data:
        mongodb:
            host: ${MONGODB_HOST:127.0.0.1}
            port: ${MONGODB_PORT:27017}
            database: ${MONGODB_DATABASE:purely_auth_service}
    jpa:
        hibernate:
            ddl-auto: update

server:
    port: 9060

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    instance:
        hostname: localhost