spring:
    application:
        name: category-service
    data:
        mongodb:
            host: 127.0.0.1
            port: 27017
            database: purely_category_service
    jpa:
        hibernate:
            ddl-auto: update

server:
    port: ${CATEGORY_SERVICE_PORT:9000}

eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka/}
    