spring:
    application:
        name: order-service
    data:
        mongodb:
            host: 127.0.0.1
            port: 27017
            database: purely_order_service
    jpa:
        hibernate:
            ddl-auto: update

server:
    port: ${ORDER_SERVICE_PORT:9070}

eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka/}