spring:
    application:
        name: user-service
    data:
        mongodb:
            host: ${MONGODB_HOST:127.0.0.1}
            port: ${MONGODB_PORT:27017}
            database: ${MONGODB_DATABASE:purely_auth_service}
    jpa:
        hibernate:
            ddl-auto: update

server:
    port: ${USER_SERVICE_PORT:9050}

eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka/}