spring:
    application:
        name: product-service
    data:
        mongodb:
            host: 127.0.0.1
            port: 27017
            database: purely_product_service
    jpa:
        hibernate:
            ddl-auto: update

server:
    port: ${PRODUCT_SERVICE_PORT:9010}

eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka/}
    instance:
        hostname: localhost