spring:
    application:
        name: product-service
    data:
        mongodb:
            host: ${MONGODB_HOST:127.0.0.1}
            port: ${MONGODB_PORT:27017}
            database: ${MONGODB_DATABASE:purely_product_service}
    jpa:
        hibernate:
            ddl-auto: update

server:
    port: ${PRODUCT_SERVICE_PORT:9010}

eureka:
    client:
        serviceUrl:
            defaultZone: ${SERVICE_REGISTRY_SERVICE_URL:http://localhost:8761/eureka/}
    instance:
        hostname: ${SERVICE_REGISTRY_HOSTNAME:localhost}