apiVersion: v1
kind: ConfigMap
metadata:
  name: purely-config
  namespace: purely
  labels:
    app: purely
data:
  # BACKEND_DOMAIN
  BACKEND_DOMAIN : "http://api.purely.com"

  # PORTS
  API_GATEWAY_PORT : "8080"
  AUTH_SERVICE_PORT : "9030"
  USER_SERVICE_PORT : "9050"
  PRODUCT_SERVICE_PORT : "9010"
  ORDER_SERVICE_PORT : "9070"
  NOTIFICATION_SERVICE_PORT : "9020"
  CATEGORY_SERVICE_PORT : "9060"
  CART_SERVICE_PORT : "9000"
  FRONTEND_PORT : "3000"

  # SERVICE-HOSTNAMEs
  API_GATEWAY_HOSTNAME : "api-gateway"
  AUTH_SERVICE_HOSTNAME : "auth-service"
  USER_SERVICE_HOSTNAME : "user-service"
  PRODUCT_SERVICE_HOSTNAME : "product-service"
  NOTIFICATION_SERVICE_HOSTNAME : "notification-service"
  ORDER_SERVICE_HOSTNAME : "order-service"
  CATEGORY_SERVICE_HOSTNAME : "category-service"
  CART_SERVICE_HOSTNAME : "cart-service"

  #DATABASES
  AUTH_DATABASE : "purely_auth_service"
  CART_DATABASE : "purely_cart_service"
  CATEGORY_DATABASE : "purely_category_service"
  ORDER_DATABASE : "purely_order_service"
  PRODUCT_DATABASE : "purely_product_service"

  #EUREKA 
  SERVICE_REGISTRY_SERVICE_URL: "http://service-registry:8761/eureka"
  SERVICE_REGISTRY_HOSTNAME: "service-registry"
  SERVICE_REGISTRY_PORT : "8761"
  
  MONGODB_PORT: "27017"
  MONGODB_HOST: "mongodb"
  MONGODB_AUTHSOURCE: "admin"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init-script
  namespace: purely
  labels:
    app: purely
data:
  init-data.js: |
    // Import required modules
    const fs = require('fs');

    // Switch to the purely_product_service database and create the 'products' collection
    db = db.getSiblingDB('purely_product_service');

    // Load products data from the JSON file
    const productsData = fs.readFileSync('/docker-entrypoint-initdb.d/products.json');
    let products = JSON.parse(productsData);

    // Convert $oid fields to ObjectId
    products = products.map(product => {
        if (product._id && product._id.$oid) {
            product._id = ObjectId(product._id.$oid);
        }
        return product;
    });
    db.products.insertMany(products);


    // Switch to the purely_category_service database and create the 'categories' collection
    db = db.getSiblingDB('purely_category_service');
    // Load categories data from the JSON file
    const categoriesData = fs.readFileSync('/docker-entrypoint-initdb.d/categories.json');
    let categories = JSON.parse(categoriesData);

    // Convert $oid fields to ObjectId
    categories = categories.map(category => {
        if (category._id && category._id.$oid) {
            category._id = ObjectId(category._id.$oid);
        }
        return category;
    });
    db.categories.insertMany(categories);

    print("Database initialization complete!");

  categories.json: |
    [{
      "_id": {
        "$oid": "6773f28a0f5832bdbc95ebbd"
      },
      "categoryName": "Fitness Equipment",
      "description": "Equipment designed to help you achieve your fitness goals, including treadmills, dumbbells, and yoga mats.",
      "imageUrl": "6773f28a0f5832bdbc95ebbd.jpg"
    },
    {
      "_id": {
        "$oid": "6773f28a0f5832bdbc95ebbe"
      },
      "categoryName": "Nutrition and Supplements",
      "description": "Products to support your nutritional needs, including protein powders, vitamins, and energy bars.",
      "imageUrl": "6773f28a0f5832bdbc95ebbe.webp"
    },
    {
      "_id": {
        "$oid": "6773f28a0f5832bdbc95ebbf"
      },
      "categoryName": "Personal Care",
      "description": "Products to help you maintain personal hygiene and well-being, such as skincare items and hair care products.",
      "imageUrl": "6773f28a0f5832bdbc95ebbf.jpg"
    },
    {
      "_id": {
        "$oid": "6773f28a0f5832bdbc95ebc0"
      },
      "categoryName": "Mental Wellness",
      "description": "Tools and resources to support mental health, including meditation apps, stress-relief items, and self-help books.",
      "imageUrl": "6773f28a0f5832bdbc95ebc0.jpg"
    },
    {
      "_id": {
        "$oid": "6773f28a0f5832bdbc95ebc1"
      },
      "categoryName": "Home Gym Essentials",
      "description": "Essential items for setting up a home gym, such as resistance bands, kettlebells, and stability balls.",
      "imageUrl": "6773f28a0f5832bdbc95ebc1.webp"
    }]

  products.json: |
    [{
      "_id": {
        "$oid": "6773f35c0f5832bdbc95ebc4"
      },
      "productName": "Yoga Mat",
      "price": 25.99,
      "description": "A high-quality yoga mat with a non-slip surface for enhanced stability and comfort.",
      "imageUrl": "https://gadgetcity.lk/wp-content/uploads/2021/07/ym6.jpg",
      "categoryId": "6773f28a0f5832bdbc95ebbd",
      "categoryName": "Fitness Equipment"
    },
    {
      "_id": {
        "$oid": "6773f35c0f5832bdbc95ebc5"
      },
      "productName": "Dumbbells Set",
      "price": 50,
      "description": "Adjustable dumbbells for a versatile home workout experience.",
      "imageUrl": "https://reach2fitness.com/cdn/shop/files/71K5nhm3lhL_1200x.jpg?v=1724981638",
      "categoryId": "6773f28a0f5832bdbc95ebbd",
      "categoryName": "Fitness Equipment"
    },
    {
      "_id": {
        "$oid": "6773f35c0f5832bdbc95ebc6"
      },
      "productName": "Protein Powder",
      "price": 45.5,
      "description": "Premium whey protein powder to support muscle recovery and growth.",
      "imageUrl": "https://www.happyway.com.au/cdn/shop/articles/calories-in-protein-shake_2048x2048.jpg?v=1529997057",
      "categoryId": "6773f28a0f5832bdbc95ebbe",
      "categoryName": "Nutrition and Supplements"
    },
    {
      "_id": {
        "$oid": "6773f35c0f5832bdbc95ebc7"
      },
      "productName": "Vitamin C Tablets",
      "price": 12.99,
      "description": "Boost your immune system with these high-quality Vitamin C tablets.",
      "imageUrl": "https://images.everydayhealth.com/images/nutrients/vitamins/possible-benefits-of-vitamin-c-supplements-1440x810.jpg",
      "categoryId": "6773f28a0f5832bdbc95ebbe",
      "categoryName": "Nutrition and Supplements"
    },
    {
      "_id": {
        "$oid": "6773f35c0f5832bdbc95ebc8"
      },
      "productName": "Face Moisturizer",
      "price": 18.75,
      "description": "A lightweight, hydrating face moisturizer suitable for all skin types.",
      "imageUrl": "https://m.media-amazon.com/images/I/51cXkIfVBtL.jpg",
      "categoryId": "6773f28a0f5832bdbc95ebbf",
      "categoryName": "Personal Care"
    },
    {
      "_id": {
        "$oid": "6773f35c0f5832bdbc95ebc9"
      },
      "productName": "Shampoo Bar",
      "price": 9.99,
      "description": "Eco-friendly and nourishing shampoo bar for healthy, shiny hair.",
      "imageUrl": "https://aspenkaynaturals.com/cdn/shop/products/image_06506f13-4eff-4564-8046-cc28dbd84af4.jpg?v=1686971291",
      "categoryId": "6773f28a0f5832bdbc95ebbf",
      "categoryName": "Personal Care"
    },
    {
      "_id": {
        "$oid": "6773f35c0f5832bdbc95ebca"
      },
      "productName": "Meditation Cushion",
      "price": 32,
      "description": "Comfortable and supportive cushion for long meditation sessions.",
      "imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMPAM4TOLlH_C-qRMmHj8LP8Cj9K5iSpOegw&s",
      "categoryId": "6773f28a0f5832bdbc95ebc0",
      "categoryName": "Mental Wellness"
    },
    {
      "_id": {
        "$oid": "6773f35c0f5832bdbc95ebcb"
      },
      "productName": "Aromatherapy Diffuser",
      "price": 24.5,
      "description": "Relax with essential oils using this easy-to-use aromatherapy diffuser.",
      "imageUrl": "https://images-cdn.ubuy.co.id/65ca214e83cec32622549c8c-wqjnweq-aroma-essential-oil-diffuser-led.jpg",
      "categoryId": "6773f28a0f5832bdbc95ebc0",
      "categoryName": "Mental Wellness"
    },
    {
      "_id": {
        "$oid": "6773f35c0f5832bdbc95ebcc"
      },
      "productName": "Resistance Bands",
      "price": 14.99,
      "description": "Durable and versatile resistance bands for strength training and flexibility exercises.",
      "imageUrl": "https://media.seniority.in/catalog/product/cache/242b55c74bcaf9102cfc5599e255893a/s/e/sen742-loopband_1_.jpg",
      "categoryId": "6773f28a0f5832bdbc95ebc1",
      "categoryName": "Home Gym Essentials"
    },
    {
      "_id": {
        "$oid": "6773f35c0f5832bdbc95ebcd"
      },
      "productName": "Stability Ball",
      "price": 19.99,
      "description": "An anti-burst stability ball perfect for yoga, Pilates, and core workouts.",
      "imageUrl": "https://lino.lk/wp-content/uploads/2018/06/yoga-ball-1-768x768.jpg",
      "categoryId": "6773f28a0f5832bdbc95ebc1",
      "categoryName": "Home Gym Essentials"
    }]