apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: purely
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: registry.xcelerate.systems/devops-project/frontend:latest # Replace with your actual image name and tag
          ports:
            - containerPort: 80
          env:
            - name: VITE_API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: purely-config
                  key: BACKEND_DOMAIN
            - name: APP_ENV_PREFIX
              value: "VITE_"
            - name: PREFIX_VALUE
              value: ""
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: purely
  labels:
    app: frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: frontend
