apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: purely
  labels:
    app: mongodb
type: Opaque
data:
  mongo-root-username: YWRtaW4= # "admin" in base64
  mongo-root-password: cGFzc3dvcmQ= # "password" in base64
---
apiVersion: v1
kind: Secret
metadata:
  name: email-secret
  namespace: purely
  labels:
    app: purely
type: Opaque
data:
  # I still need to replace these with the actual values
  EMAIL_USERNAME: ZGVtb0BnbWFpbC5jb20= ######################
  EMAIL_PASSWORD: cGFzc3dvcmQ= # "password" in base64
  SMTP_SERVER_URL: c3RyaW5nLmV4YW1wbGUuY29t # "string.example.com" in base64
  SMTP_SERVER_PORT: NTQz # "543" in base64