apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: {{ .Values.namespace }}
  labels:
    app: api-gateway
spec:
  selector:
    matchLabels:
      app: api-gateway
  replicas: {{ .Values.api.gateway.replicas }}
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: {{ .Values.global.registry }}/{{ .Values.global.repository }}/api-gateway:{{ .Values.global.imageTag }}
          ports:
            - containerPort: {{ .Values.api.gateway.port }}
          resources:
            {{- toYaml .Values.api.gateway.resources | nindent 12 }}
          env:
            - name: API_GATEWAY_PORT
              valueFrom:
                configMapKeyRef:
                  name: purely-config
                  key: API_GATEWAY_PORT
            - name: SERVICE_REGISTRY_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: purely-config
                  key: SERVICE_REGISTRY_SERVICE_URL
            - name: SERVICE_REGISTRY_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: purely-config
                  key: API_GATEWAY_HOSTNAME
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: {{ .Values.namespace }}
  labels:
    app: api-gateway
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.api.gateway.port }}
      targetPort: {{ .Values.api.gateway.port }}
  selector:
    app: api-gateway