apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.global.registry }}/{{ .Values.global.repository }}/frontend:{{ default .Values.global.defaultImageTag .Values.frontend.imageTag }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
          env:
            - name: VITE_API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: purely-config
                  key: BACKEND_DOMAIN
            - name: APP_ENV_PREFIX
              value: "VITE_"
            - name: PREFIX_VALUE
              value: ""
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: frontend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
  selector:
    app: frontend