apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.frontend.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: {{ .Values.frontend.port }}
    
    - host: eureka.{{ .Values.frontend.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service-registry
                port:
                  number: {{ .Values.serviceRegistry.port }}

    - host: {{ .Values.api.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: {{ .Values.api.gateway.port }}