apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: mongodb
type: Opaque
data:
  mongo-root-username: {{ .Values.mongodb.auth.rootUser | b64enc }}
  mongo-root-password: {{ .Values.mongodb.auth.rootPassword | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: email-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: purely
type: Opaque
data:
  EMAIL_USERNAME: {{ .Values.email.smtp.username | b64enc }}
  EMAIL_PASSWORD: {{ .Values.email.smtp.password | b64enc }}
  SMTP_SERVER_URL: {{ .Values.email.smtp.server | b64enc }}
  SMTP_SERVER_PORT: {{ .Values.email.smtp.port | toString | b64enc }}