global:
  registry: registry.xcelerate.systems
  repository: devops-project
  defaultImageTag: latest
namespace: purely
mongodb:
  auth:
    rootUser: "${MONGODB_USERNAME}"
    rootPassword: "${MONGODB_PASSWORD}"
  persistence:
    size: 1Gi
  port: 27017
  initData:
    enabled: true
    initScript:
      name: init-mongo.js
      configMapKey: init-mongo.js
    sampleData:
      products:
        name: products.json
        configMapKey: products.json
      categories:
        name: categories.json
        configMapKey: categories.json
api:
  domain: api.purely.com
  gateway:
    imageTag: ""
    port: 8080
    replicas: 1
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "500m"
serviceRegistry:
  imageTag: ""
  port: 8761
  replicas: 1
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"
services:
  auth:
    imageTag: ""
    port: 9030
    replicas: 1
  user:
    imageTag: ""
    port: 9050
    replicas: 1
  product:
    imageTag: ""
    port: 9010
    replicas: 1
  order:
    imageTag: ""
    port: 9070
    replicas: 1
  notification:
    imageTag: ""
    port: 9020
    replicas: 1
  category:
    imageTag: ""
    port: 9060
    replicas: 1
  cart:
    imageTag: ""
    port: 9000
    replicas: 1
frontend:
  imageTag: "1b51c30"
  domain: purely.com
  port: 80
  replicas: 1
ingress:
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
email:
  smtp:
    server: "${SMTP_SERVER}"
    port: "${SMTP_PORT}"
    username: "${SMTP_USERNAME}"
    password: "${SMTP_PASSWORD}"
